name: Hosting nodejs app
on:
  push: 
    branches:
      - main
      
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out code
        uses: actions/checkout@v3
        
      - name: Set up Nodejs  version
        uses: actions/setup-node@v3   
        with: 
         node-version: '18.x'
         
      - name: Install the node modules
        run: npm install
        
     
        
      - name: Upload the node modules for next jobs
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: ./node_modules
          
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    
    
    steps: 
    - name: checkout code
      uses: actions/checkout@v3
    - name: Downoad the artifact from the build job that we uploaded
      uses: actions/download-artifact@v3
      with:
          name: node_modules
          path: ./node_modules
          
    - name: Set up ssh key
      run: |
          echo "${{secrets.PRIVATE_KEY}}" >> key.pem
          chmod 600 key.pem
  
    - name: copy files to ec2
      run: |
        scp -i key.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -r ./* ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu
       
   
    - name: Install Mysql
      run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} 'sudo apt-get update -y && sudo apt-get install mysql-server -y'
    
    - name: Start MySQL service
      run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} 'sudo systemctl start mysql'
    
    
    
    - name: Create Mysql User
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} << EOF
        sudo mysql -u root -e "CREATE USER IF NOT EXISTS 'sush'@'localhost' IDENTIFIED BY 'sush123';
        GRANT ALL PRIVILEGES ON *.* TO 'sush'@'localhost';
        FLUSH PRIVILEGES;"
        exit
        EOF

    - name: Create database using the user we just created 
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} << EOF
        sudo mysql -u sush -psush123 -e "CREATE DATABASE IF NOT EXISTS my_db;"
        EOF

    - name: Create Table
      run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP}} 'mysql -u sush -psush123 -h localhost  -D my_db -e "CREATE TABLE employee (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone VARCHAR(255), email VARCHAR(255), address VARCHAR(255));"'
      
          
          
   
   
    - name: install PM2 and Start Node
      run: | 
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ubuntu@${{ secrets.EC2_IP}} '
          sudo apt install -g pm2 -y
          '
   
   
   
    
    - name: start node app with pm2 Process manager    
      run: |
        ssh -i key.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        ubuntu@${{secrets.EC2_IP}} \
        'chmod +x /home/ubuntu/pm2.sh && cd /home/ubuntu && ./pm2.sh start app.js'
         
