name: Hosting nodejs app
on:
  push: 
    branches:
      - main
      
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out code
        uses: actions/checkout@v3
        
      - name: Set up Nodejs  version
        uses: actions/setup-node@v3   
        with: 
         node-version: '18.x'
         
      - name: Install the node modules
        run: npm install
        
     
        
      - name: Upload the node modules for next jobs
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: ./node_modules
          
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    
    
    steps: 
    - name: checkout code
      uses: actions/checkout@v3
    - name: Downoad the artifact from the build job that we uploaded
      uses: actions/download-artifact@v3
      with:
          name: node_modules
          path: ./node_modules
          
    - name: Set up ssh key
      run: |
          echo "{{secrets.PRIVATE_KEY}}" >> key.pem
          chmod 600 key.pem
  
    - name: copy files to ec2
      run: |
        scp -i key.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -r ./* ubuntu@34.207.192.176:/app/
       
   
    - name: Install Mysql
      run: |
         ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_IP }} 'sudo apt-get update -y && sudo apt-get install mysql-client -y'

    - name: Create Mysql User
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_IP }}'
        mysql -u root -e "CREATE USER 'sush'@'localhost' IDENTIFIED BY 'sush123';"'
        mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sush'@'localhost';"
        FLUSH PRIVILEGES;'
    - name: Create database using the user we just created 
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_IP }} 'mysql -u sush -psush123 -h localhost -e "CREATE DATABASE my_db;"'

    - name: Create Table
      run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_IP}} 
          'mysql -u sush -psush123 -h localhost  -D my_db -e "CREATE TABLE employee (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone VARCHAR(255), email VARCHAR(255), address VARCHAR(255));"'
      
          
          
   
    
    - name: start node app with pm2 Process manager    
      run: |
        ssh -i key.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        ubuntu@${{secrets.EC2_IP}} \
        'chmod +x /app/pm2.sh && cd /app && ./pm2.sh'
         
