name: Hosting nodejs app
on:
  push: 
    branches:
      - main
      
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out code
        uses: actions/checkout@v3
        
      - name: Set up Nodejs  version
        uses: actions/setup-node@v3   
        with: 
         node-version: '18.x'
         
      - name: Install the node modules
        run: npm install
        
   
        
      - name: Upload the node modules for next jobs
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: ./node_modules
          
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    
    
    steps: 
    - name: checkout code
      uses: actions/checkout@v3
    - name: Downoad the artifact from the build job that we uploaded
      uses: actions/download-artifact@v3
      with:
          name: node_modules
          path: ./node_modules
          
    - name: Set up ssh key
      run: |
          echo "${{secrets.PRIVATE_KEY}}" >> key.pem
          chmod 600 key.pem
  
    - name: copy files to ec2
      run: |
        scp -i key.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -r ./* ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu
       
   
    - name: Install Mysql
      run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} 'sudo apt-get update -y && sudo apt-get install mysql-server -y'
    
    - name: Start MySQL service
      run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} 'sudo systemctl start mysql'
    
    
    
    - name: Create Mysql User
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} << EOF
        sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
        sudo mysql -u root -e "CREATE USER IF NOT EXISTS 'sush'@'%' IDENTIFIED WITH mysql_native_password BY 'sush123';"
        sudo mysql -u root -e "GRANT USAGE ON *.* TO 'sush'@'%';"
        sudo mysql -u root -e "ALTER USER 'sush'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
        sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sush1'@'%';"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
        exit
        EOF



    - name: Create database using the user we just created 
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} << EOF
        sudo mysql -u sush -psush123 -e "CREATE DATABASE IF NOT EXISTS my_db;"
        EOF

    - name: Create Table
      run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP}} 'mysql -u sush -psush123 -h localhost  -D my_db -e "CREATE TABLE IF NOT EXISTS employee (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone VARCHAR(255), email VARCHAR(255), address VARCHAR(255));"'
    - name: Install pm2
      run: |
       ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_IP }} '
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash &&
        export NVM_DIR="$HOME/.nvm" &&
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" &&
        nvm install --lts
        cd /home/ubuntu &&
        npm install
        node app.js
        '
        
      # npm install pm2 -g
       # chmod +x pm2.sh
        #./pm2.sh start app.js
       

#     - name: Start node app with pm2 Process manager
#       run: |
#         ssh -i key.pem \
#           -o StrictHostKeyChecking=no \
#           -o UserKnownHostsFile=/dev/null \
#           ubuntu@${{ secrets.EC2_IP }} \
#           'cd /home/ubuntu && chmod +x pm2.sh && /usr/local/bin/pm2 start app.js'
